modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="metahumans"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="NexGEN26"
description='''
Give users/players metahuman powers
'''

[[dependencies.metahumans]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
